### ISSUE TITLE
ImportError: DLL load failed while importing _dlib_pybind11: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by VasilijKolomiets** [conda-forge/dlib-feedstock#52]
Issue:
 I work in:

Windows10
CUDA10.1
Anaconda
Python 3.8

<br/>
Environment (<code>conda list</code>):
<details>

```
(dlib) C:\Users\Vasil>conda list
# packages in environment at D:\Games\conda\envs\dlib:
#
# Name                    Version                   Build  Channel
ca-certificates           2020.12.5            h5b45459_0    conda-forge
certifi                   2020.12.5        py38haa244fe_1    conda-forge
dlib                      19.21.1          py38h082dfc2_0    conda-forge
intel-openmp              2020.3             h57928b3_311    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
numpy                     1.20.1           py38h0cc643e_0    conda-forge
openssl                   1.1.1k               h8ffe710_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
python                    3.8.8           h7840368_0_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
setuptools                49.6.0           py38haa244fe_3    conda-forge
sqlite                    3.35.3               h8ffe710_0    conda-forge
vc                        14.2                 hb210afc_4    conda-forge
vs2015_runtime            14.28.29325          h5e1d092_4    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wincertstore              0.2             py38haa244fe_1006    conda-forge
zlib                      1.2.11            h62dcd97_1010    conda-forge

(dlib) C:\Users\Vasil>

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
    active environment : dlib
    active env location : D:\Games\conda\envs\dlib
            shell level : 1
       user config file : C:\Users\Vasil\.condarc
 populated config files : C:\Users\Vasil\.condarc
          conda version : 4.9.2
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.2=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : D:\Games\conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Games\conda\pkgs
                          C:\Users\Vasil\.conda\pkgs
                          C:\Users\Vasil\AppData\Local\conda\conda\pkgs
       envs directories : D:\Games\conda\envs
                          C:\Users\Vasil\.conda\envs
                          C:\Users\Vasil\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

```
</details>

All I did - just install **dlib** in new env and try to do import:     

```
(dlib) C:\Users\Vasil>conda install dlib
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: D:\Games\conda\envs\dlib

  added / updated specs:
    - dlib


The following NEW packages will be INSTALLED:

  dlib               conda-forge/win-64::dlib-19.21.1-py38h082dfc2_0
  intel-openmp       conda-forge/win-64::intel-openmp-2020.3-h57928b3_311
  jpeg               conda-forge/win-64::jpeg-9d-h8ffe710_0
  libblas            conda-forge/win-64::libblas-3.9.0-8_mkl
  libcblas           conda-forge/win-64::libcblas-3.9.0-8_mkl
  liblapack          conda-forge/win-64::liblapack-3.9.0-8_mkl
  libpng             conda-forge/win-64::libpng-1.6.37-h1d00b33_2
  mkl                conda-forge/win-64::mkl-2020.4-hb70f87d_311
  numpy              conda-forge/win-64::numpy-1.20.1-py38h0cc643e_0
  zlib               conda-forge/win-64::zlib-1.2.11-h62dcd97_1010


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(dlib) C:\Users\Vasil>python
Python 3.8.8 | packaged by conda-forge | (default, Feb 20 2021, 15:50:08) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  
  File "D:\Games\conda\envs\dlib\lib\site-packages\dlib\__init__.py", line 19, in <module>
    from _dlib_pybind11 import *
ImportError: DLL load failed while importing _dlib_pybind11: A dynamic link library (DLL) initialization routine failed.
```
Can anybody help a bit?

I was [here](https://github.com/davisking/dlib/issues/2039).  
and that's why here my bin directory and path
`
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
CUDA_PATH_V10_1=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
...
PATH=D:\Games\conda\envs\dlib;D:\Games\conda\envs\dlib\Library\mingw-w64\bin;D:\Games\conda\envs\dlib\Library\usr\bin;D:\Games\conda\envs\dlib\Library\bin;D:\Games\conda\envs\dlib\Scripts;D:\Games\conda\envs\dlib\bin;D:\Games\conda\condabin;D:\Games\conda;D:\Games\conda\Library\mingw-w64\bin;D:\Games\conda\Library\usr\bin;D:\Games\conda\Library\bin;D:\Games\conda\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.3.0;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\PuTTY;D:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\Program Files\dotnet;C:\Users\Vasil\AppData\Local\Microsoft\WindowsApps;C:\Users\Vasil\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Vasil\AppData\Local\GitHubDesktop\bin;C:\Users\Vasil\AppData\Local\Microsoft\WindowsApps;d:\Program Files\heroku\bin;C:\Users\Vasil\AppData\Roaming\npm;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin;.
`
and **cudnn64_7.dll**  is in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin

**Comment by VasilijKolomiets** [comment]
I have installed version Dlib 19.7.0. on python 3,6.13

`pip install https://pypi.python.org/packages/da/06/bd3e241c4eb0a662914b3b4875fc52dd176a9db0d4a2c915ac2ad8800e9e/dlib-19.7.0-cp36-cp36m-win_amd64.whl#md5=b7330a5b2d46420343fbed5df69e6a3f
`

all works... but may be any advices about new versions?

**Comment by Tobias-Fischer** [comment]
Is this still an issue with newer versions installed via conda @VasilijKolomiets?

**Comment by Tobias-Fischer** [comment]
Closing - it would surprise me if this is still an issue.
